# Generated by Django 5.0.3 on 2024-03-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_employee', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('regular', 'Regular')], max_length=50)),
                ('core_area', models.CharField(choices=[('webdeveloper', 'Web Developer'), ('graphicdesigner', 'Graphic Designer'), ('seoengineer', 'SEO Engineer'), ('softwaredeveloper', 'Software Developer')], max_length=50)),
                ('reporting_supervisor', models.CharField(choices=[('alishoaibzaidi', 'Ali Shoaib Zaidi'), ('zaynalinaqvi', 'Zayn Ali Naqvi'), ('syedmujtaba', 'Syed Mujtaba'), ('aijazmahdavi', 'Aijaz Mahdavi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary')], max_length=10)),
                ('cnic', models.BigIntegerField()),
                ('cnicFront', models.ImageField(null=True, upload_to='')),
                ('cnicBack', models.ImageField(null=True, upload_to='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Other_Professional_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_job', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('job_period_from', models.DateField()),
                ('job_period_to', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_degree', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=2)),
                ('year_of_passing', models.IntegerField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('current', 'Current'), ('alternative', 'Alternative')], max_length=50)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('present', 'Present'), ('permanent', 'Permanent')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Religious_Or_Political_Af',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name_of_party', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_taught', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('teaching_period_from', models.DateField()),
                ('teaching_period_to', models.DateField()),
                ('age_group_taught', models.IntegerField()),
                ('references_name', models.CharField(max_length=50)),
                ('references_contact_no', models.BigIntegerField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMAdmin.personalinfo')),
            ],
        ),
    ]
